In [1]:
import numpy as np




In [2]:
#Project:Basic Data analytics operations

#Create a numpy array
data = np.arange(10)
print("1D Array:")
print(data)


1D Array:
[0 1 2 3 4 5 6 7 8 9]


In [3]:
#Reshape the array
reshaped_data=data.reshape(2,5)
print("\nReshaped Array:")
print(reshaped_data)


Reshaped Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [4]:
#Basic Statistics
#Mean
mean_value=np.mean(data)
print("\nMean of the data:")
print(mean_value)


Mean of the data:
4.5


In [5]:
#median
median_value=np.median(data)
print("\nMedian of the data:")
print(median_value)


Median of the data:
4.5


In [6]:
#Standard deviation
std_deviation=np.std(data)
print("\nStandard deviation of the data:")
print(std_deviation)



Standard deviation of the data:
2.8722813232690143


In [15]:
#Array operations
data2=np.array([10,20,30,40,50,60,70,80,90,100])

In [16]:
#Adding
added_data = data + data2
print("\nAdded array:")
print(added_data)


Added array:
[ 10  21  32  43  54  65  76  87  98 109]


In [17]:
#Substract
sub_data = data - data2
print("\nSubtracted array:")
print(sub_data)



Subtracted array:
[-10 -19 -28 -37 -46 -55 -64 -73 -82 -91]


In [18]:
#Multiply
mul_data = data * data2
print("\nMultiplied array:")
print(mul_data)



Multiplied array:
[  0  20  60 120 200 300 420 560 720 900]


In [19]:
#Divide
div_data = data2 / (data+1)
print("\nDivided data:")
print(div_data)


Divided data:
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


In [20]:
#boolean indexing
boo_data = data > 5
print("\nBoolean data > 5")
print(boo_data)



Boolean data > 5
[False False False False False False  True  True  True  True]


In [22]:
filter_data = data[boo_data]
print("\nFiltered data:")
print(filter_data)



Filtered data:
[6 7 8 9]


In [23]:
#slicing
fi_row = reshaped_data[0,:]
print("\nFirst row of reshaped data")
print(fi_row)


First row of reshaped data
[0 1 2 3 4]


In [26]:
#splitting
sp_data=np.split(reshaped_data,2)
print("\nSplit data into two subs:")
print(sp_data)


Split data into two subs:
[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]


In [27]:
#merging
mer_data=np.concatenate(sp_data)
print("\nMerged data:")
print(mer_data)


Merged data:
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [29]:
#stacking
array1 = np.array(([1,2],[3,4]))
array2 = np.array(([5,6],[7,8]))



In [30]:
#vertical stacking
vsta_data = np.vstack((array1,array2))
print("\nVertical stacked data:")
print(vsta_data)


Vertical stacked data:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [31]:
#horzintal stacking
hsta_data = np.hstack((array1,array2))
print("\nHorizontal stacked data:")
print(hsta_data)


Horizontal stacked data:
[[1 2 5 6]
 [3 4 7 8]]


In [32]:
np.save('data.npy',data)